language: go

go:
  - "1.11"
  - tip

install:
  - go get -t ./...

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release  && chmod +x ~/semantic-release && ~/semantic-release -vf
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
